/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Get Fortress version */
export declare function getVersion(): string
/** Execute a simple test command */
export declare function testCommand(args: Array<string>): string
/** Simple Fortress CLI wrapper */
export declare class FortressCli {
  /** Create new CLI instance */
  constructor()
  /** Get version information */
  version(): string
  /** Get help information */
  help(): string
  /** Execute test command */
  test(args?: Array<string> | undefined | null): string
}
