{{- if .Values.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "fortress.fullname" . }}-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fortress.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
  {{- with .Values.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
{{- end }}
---
{{- if .Values.logsPersistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "fortress.fullname" . }}-logs
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fortress.labels" . | nindent 4 }}
    app.kubernetes.io/component: logs
  {{- with .Values.logsPersistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- toYaml .Values.logsPersistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.logsPersistence.size }}
  {{- if .Values.logsPersistence.storageClass }}
  storageClassName: {{ .Values.logsPersistence.storageClass }}
  {{- end }}
{{- end }}
