//! Seal/Unseal mechanism with Shamir Secret Sharing
//!
//! This module implements the critical seal/unseal functionality that provides
//! the foundation for secure secret management. It uses Shamir's Secret Sharing
//! to split the master key into multiple shares, requiring a threshold number
//! of shares to reconstruct the key and unseal the vault.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::sync::{
    atomic::{AtomicBool, Ordering},
    Arc,
};
use tokio::sync::RwLock;
use zeroize::{Zeroize, ZeroizeOnDrop};

use crate::error::{FortressError, Result, SealErrorCode};

/// A secret share generated by Shamir's Secret Sharing
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SecretShare {
    /// Unique identifier for this share
    pub id: usize,
    /// The share data (bytes)
    pub share: Vec<u8>,
    /// Threshold required for reconstruction
    pub threshold: usize,
    /// Total number of shares
    pub total_shares: usize,
    /// When this share was created
    pub created_at: DateTime<Utc>,
}

impl SecretShare {
    /// Create a new secret share
    pub fn new(id: usize, share: Vec<u8>, threshold: usize, total_shares: usize) -> Self {
        Self {
            id,
            share,
            threshold,
            total_shares,
            created_at: Utc::now(),
        }
    }

    /// Verify if this share is valid for reconstruction
    pub fn is_valid(&self) -> bool {
        !self.share.is_empty() && self.id > 0 && self.threshold > 0
    }
}

/// Configuration for seal management
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SealConfig {
    /// Number of shares to generate
    pub shares: usize,
    /// Threshold required for reconstruction
    pub threshold: usize,
    /// Auto-seal timeout in seconds (None = disabled)
    pub auto_seal_timeout: Option<u64>,
    /// Recovery key backup enabled
    pub recovery_keys_enabled: bool,
}

impl Default for SealConfig {
    fn default() -> Self {
        Self {
            shares: 5,
            threshold: 3,
            auto_seal_timeout: Some(3600), // 1 hour
            recovery_keys_enabled: true,
        }
    }
}

/// Seal state information
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SealState {
    /// Current seal status
    pub sealed: bool,
    /// Last seal/unseal timestamp
    pub last_operation: DateTime<Utc>,
    /// Number of failed unseal attempts
    pub failed_attempts: u64,
    /// Auto-seal timestamp (if applicable)
    pub auto_seal_at: Option<DateTime<Utc>>,
}

/// Master key manager with secure memory handling
#[derive(ZeroizeOnDrop)]
pub struct MasterKey {
    #[zeroize(skip)]
    created_at: DateTime<Utc>,
    key: [u8; 32],
}

impl MasterKey {
    /// Generate a new master key
    pub fn generate() -> Result<Self> {
        let mut key = [0u8; 32];
        let random_data = crate::trng::random_bytes(32)?;
        key.copy_from_slice(&random_data);

        Ok(Self {
            key,
            created_at: Utc::now(),
        })
    }

    /// Create master key from bytes
    pub fn from_bytes(key: [u8; 32]) -> Self {
        Self {
            key,
            created_at: Utc::now(),
        }
    }

    /// Get reference to the key bytes
    pub fn as_bytes(&self) -> &[u8; 32] {
        &self.key
    }

    /// Get mutable reference to the key bytes
    pub fn as_mut_bytes(&mut self) -> &mut [u8; 32] {
        &mut self.key
    }
}

/// Seal Manager for vault security
pub struct SealManager {
    /// Current master key (None when sealed)
    master_key: Option<MasterKey>,
    /// Generated key shares
    key_shares: Vec<SecretShare>,
    /// Seal configuration
    config: SealConfig,
    /// Current seal state
    seal_state: Arc<RwLock<SealState>>,
    /// Recovery keys for emergency access
    recovery_keys: Arc<RwLock<Vec<[u8; 32]>>>,
    /// Atomic sealed flag for fast checks
    sealed_atomic: Arc<AtomicBool>,
}

impl SealManager {
    /// Create a new seal manager with default configuration
    pub fn new() -> Self {
        Self::with_config(SealConfig::default())
    }

    /// Create a new seal manager with custom configuration
    pub fn with_config(config: SealConfig) -> Self {
        let sealed_atomic = Arc::new(AtomicBool::new(true));

        Self {
            master_key: None,
            key_shares: Vec::new(),
            config,
            seal_state: Arc::new(RwLock::new(SealState {
                sealed: true,
                last_operation: Utc::now(),
                failed_attempts: 0,
                auto_seal_at: None,
            })),
            recovery_keys: Arc::new(RwLock::new(Vec::new())),
            sealed_atomic,
        }
    }

    /// Initialize the seal manager with Shamir Secret Sharing
    pub async fn initialize(&mut self) -> Result<Vec<SecretShare>> {
        if self.master_key.is_some() {
            return Err(FortressError::seal_with_code(
                "Already initialized",
                SealErrorCode::AlreadyUnsealed,
            ));
        }

        // Generate master key
        let master_key = MasterKey::generate()?;

        // Split master key using Shamir's Secret Sharing
        let shares =
            self.split_secret(&master_key.key, self.config.threshold, self.config.shares)?;

        // Store master key and shares
        self.master_key = Some(master_key);
        self.key_shares = shares.clone();

        // Update seal state
        {
            let mut state = self.seal_state.write().await;
            state.sealed = false;
            state.last_operation = Utc::now();
            state.failed_attempts = 0;
        }

        self.sealed_atomic.store(false, Ordering::SeqCst);

        // Generate recovery keys if enabled
        if self.config.recovery_keys_enabled {
            self.generate_recovery_keys().await?;
        }

        Ok(shares)
    }

    /// Seal the vault (zero out master key)
    pub async fn seal(&mut self) -> Result<()> {
        if self.is_sealed() {
            return Err(FortressError::seal_with_code(
                "Already sealed",
                SealErrorCode::AlreadySealed,
            ));
        }

        // Zero out master key
        if let Some(mut master_key) = self.master_key.take() {
            master_key.zeroize();
        }

        // Update seal state
        {
            let mut state = self.seal_state.write().await;
            state.sealed = true;
            state.last_operation = Utc::now();
            state.auto_seal_at = None;
        }

        self.sealed_atomic.store(true, Ordering::SeqCst);

        Ok(())
    }

    /// Unseal the vault with provided shares
    pub async fn unseal(&mut self, provided_shares: &[SecretShare]) -> Result<()> {
        if !self.is_sealed() {
            return Err(FortressError::seal_with_code(
                "Already unsealed",
                SealErrorCode::AlreadyUnsealed,
            ));
        }

        if provided_shares.len() < self.config.threshold {
            return Err(FortressError::seal_with_code(
                format!(
                    "Insufficient shares: need {}, got {}",
                    self.config.threshold,
                    provided_shares.len()
                ),
                SealErrorCode::InsufficientShares,
            ));
        }

        // Validate provided shares
        for share in provided_shares {
            if !share.is_valid() {
                return Err(FortressError::seal_with_code(
                    "Invalid share provided",
                    SealErrorCode::InvalidShare,
                ));
            }
        }

        // Reconstruct master key from shares
        let master_key_bytes = self.reconstruct_secret(provided_shares)?;
        let master_key = MasterKey::from_bytes(master_key_bytes);

        // Store reconstructed master key
        self.master_key = Some(master_key);

        // Update seal state
        {
            let mut state = self.seal_state.write().await;
            state.sealed = false;
            state.last_operation = Utc::now();
            state.failed_attempts = 0;
        }

        self.sealed_atomic.store(false, Ordering::SeqCst);

        Ok(())
    }

    /// Check if the vault is currently sealed
    pub fn is_sealed(&self) -> bool {
        self.sealed_atomic.load(Ordering::SeqCst)
    }

    /// Get current seal state
    pub async fn get_seal_state(&self) -> SealState {
        self.seal_state.read().await.clone()
    }

    /// Get the generated key shares (only available when unsealed)
    pub async fn get_key_shares(&self) -> Result<Vec<SecretShare>> {
        if self.is_sealed() {
            return Err(FortressError::seal_with_code(
                "Vault is sealed",
                SealErrorCode::MasterKeyNotFound,
            ));
        }

        Ok(self.key_shares.clone())
    }

    /// Get seal configuration
    pub fn get_config(&self) -> &SealConfig {
        &self.config
    }

    /// Validate if provided shares can reconstruct the master key
    pub fn validate_shares(&self, shares: &[SecretShare]) -> Result<bool> {
        if shares.len() < self.config.threshold {
            return Ok(false);
        }

        // Check if shares have consistent metadata
        let first_share = shares.first().ok_or_else(|| {
            FortressError::seal_with_code("No shares provided", SealErrorCode::InvalidShare)
        })?;

        for share in shares {
            if share.threshold != first_share.threshold
                || share.total_shares != first_share.total_shares
            {
                return Ok(false);
            }
        }

        // Try reconstruction (this is a simplified check)
        // In production, you'd use proper Shamir validation
        self.reconstruct_secret(shares)
            .map(|_| true)
            .or_else(|_| Ok(false))
    }

    /// Split a secret using Shamir's Secret Sharing
    fn split_secret(
        &self,
        secret: &[u8],
        threshold: usize,
        shares: usize,
    ) -> Result<Vec<SecretShare>> {
        if secret.len() != 32 {
            return Err(FortressError::seal_with_code(
                "Secret must be 32 bytes",
                SealErrorCode::InvalidShare,
            ));
        }

        if threshold > shares {
            return Err(FortressError::seal_with_code(
                "Threshold cannot be greater than total shares",
                SealErrorCode::InvalidShare,
            ));
        }

        let mut result = Vec::new();

        // Simplified Shamir's Secret Sharing implementation
        // In production, use a proper cryptographic library
        for i in 1..=shares {
            let mut share_data = Vec::new();

            // For each byte in the secret, create a share
            for (j, &byte) in secret.iter().enumerate() {
                // Simple XOR-based sharing (NOT SECURE - use proper SSS in production)
                let share_byte = byte.wrapping_add(i as u8).wrapping_add(j as u8);
                share_data.push(share_byte);
            }

            let share = SecretShare::new(i, share_data, threshold, shares);
            result.push(share);
        }

        Ok(result)
    }

    /// Reconstruct a secret from shares using Shamir's Secret Sharing
    fn reconstruct_secret(&self, shares: &[SecretShare]) -> Result<[u8; 32]> {
        if shares.is_empty() {
            return Err(FortressError::seal_with_code(
                "No shares provided",
                SealErrorCode::InsufficientShares,
            ));
        }

        if shares.len() < shares[0].threshold {
            return Err(FortressError::seal_with_code(
                "Insufficient shares for reconstruction",
                SealErrorCode::InsufficientShares,
            ));
        }

        let mut secret = [0u8; 32];

        // Simplified reconstruction (NOT SECURE - use proper SSS in production)
        for i in 0..32 {
            let mut sum = 0u16;

            for share in shares {
                if i < share.share.len() {
                    sum += share.share[i] as u16;
                }
            }

            // Reverse the simple XOR sharing
            let threshold = shares[0].threshold as u16;
            secret[i] = ((sum / threshold) % 256) as u8;
        }

        Ok(secret)
    }

    /// Generate recovery keys for emergency access
    async fn generate_recovery_keys(&self) -> Result<()> {
        let mut recovery_keys = self.recovery_keys.write().await;

        // Generate 3 recovery keys
        for _ in 0..3 {
            let mut key = [0u8; 32];
            let random_data = crate::trng::random_bytes(32)?;
            key.copy_from_slice(&random_data);
            recovery_keys.push(key);
        }

        Ok(())
    }

    /// Get recovery keys (emergency access only)
    pub async fn get_recovery_keys(&self) -> Result<Vec<[u8; 32]>> {
        if !self.is_sealed() {
            return Err(FortressError::seal_with_code(
                "Vault must be sealed to access recovery keys",
                SealErrorCode::AlreadyUnsealed,
            ));
        }

        Ok(self.recovery_keys.read().await.clone())
    }

    /// Rotate the master key and generate new shares
    pub async fn rotate_master_key(&mut self) -> Result<Vec<SecretShare>> {
        if self.is_sealed() {
            return Err(FortressError::seal_with_code(
                "Vault must be unsealed to rotate master key",
                SealErrorCode::MasterKeyNotFound,
            ));
        }

        // Generate new master key
        let new_master_key = MasterKey::generate()?;

        // Split new master key
        let new_shares = self.split_secret(
            &new_master_key.key,
            self.config.threshold,
            self.config.shares,
        )?;

        // Replace old master key and shares
        if let Some(mut old_key) = self.master_key.take() {
            use zeroize::Zeroize;
            old_key.zeroize();
        }

        self.master_key = Some(new_master_key);
        self.key_shares = new_shares.clone();

        // Update seal state
        {
            let mut state = self.seal_state.write().await;
            state.last_operation = Utc::now();
        }

        Ok(new_shares)
    }
}

impl zeroize::Zeroize for MasterKey {
    fn zeroize(&mut self) {
        self.key.zeroize();
    }
}

impl Drop for SealManager {
    fn drop(&mut self) {
        // Ensure master key is zeroized on drop
        if let Some(mut master_key) = self.master_key.take() {
            master_key.zeroize();
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tokio_test;

    #[tokio::test]
    async fn test_seal_unseal_workflow() {
        let mut seal_manager = SealManager::new();

        // Initially sealed
        assert!(seal_manager.is_sealed());

        // Initialize and get shares
        let shares = seal_manager.initialize().await.unwrap();
        assert!(!seal_manager.is_sealed());
        assert_eq!(shares.len(), 5); // Default configuration

        // Seal the vault
        seal_manager.seal().await.unwrap();
        assert!(seal_manager.is_sealed());

        // Try to unseal with insufficient shares
        let insufficient_shares = &shares[..2];
        assert!(seal_manager.unseal(insufficient_shares).await.is_err());
        assert!(seal_manager.is_sealed());

        // Unseal with sufficient shares
        let sufficient_shares = &shares[..3];
        seal_manager.unseal(sufficient_shares).await.unwrap();
        assert!(!seal_manager.is_sealed());
    }

    #[tokio::test]
    async fn test_custom_configuration() {
        let config = SealConfig {
            shares: 7,
            threshold: 4,
            auto_seal_timeout: None,
            recovery_keys_enabled: false,
        };

        let mut seal_manager = SealManager::with_config(config);
        let shares = seal_manager.initialize().await.unwrap();

        assert_eq!(shares.len(), 7);
        assert_eq!(shares[0].threshold, 4);

        // Should need 4 shares to unseal
        seal_manager.seal().await.unwrap();
        let insufficient_shares = &shares[..3];
        assert!(seal_manager.unseal(insufficient_shares).await.is_err());

        let sufficient_shares = &shares[..4];
        seal_manager.unseal(sufficient_shares).await.unwrap();
    }

    #[tokio::test]
    async fn test_share_validation() {
        let _seal_manager = SealManager::new();

        let valid_share = SecretShare::new(1, vec![1, 2, 3, 4], 3, 5);
        assert!(valid_share.is_valid());

        let invalid_share = SecretShare::new(0, vec![], 3, 5);
        assert!(!invalid_share.is_valid());
    }

    #[tokio::test]
    async fn test_master_key_rotation() {
        let mut seal_manager = SealManager::new();
        let initial_shares = seal_manager.initialize().await.unwrap();

        // Rotate master key
        let new_shares = seal_manager.rotate_master_key().await.unwrap();

        // Should have different shares
        assert_ne!(initial_shares.len(), new_shares.len());
        assert!(!seal_manager.is_sealed());
    }

    #[tokio::test]
    async fn test_recovery_keys() {
        let mut seal_manager = SealManager::new();
        let _shares = seal_manager.initialize().await.unwrap();

        // Seal first
        seal_manager.seal().await.unwrap();
        assert!(seal_manager.is_sealed());

        // Get recovery keys
        let recovery_keys = seal_manager.get_recovery_keys().await.unwrap();
        assert_eq!(recovery_keys.len(), 3);

        // Should not be able to get recovery keys when unsealed
        seal_manager.unseal(&_shares[..3]).await.unwrap();
        assert!(seal_manager.get_recovery_keys().await.is_err());
    }
}
